<script lang="ts">
    import { Switch } from '@skeletonlabs/skeleton-svelte';
    import Page from '../components/Page.svelte';
    import Field from '../components/Field.svelte';
    import Notice from '../components/Notice.svelte';
    import Strength from '../components/Strength.svelte';
    import Feature from '../components/Feature.svelte';
    import Setting from '../components/Setting.svelte';
    import DataTable from '../components/DataTable.svelte';
    import AdminPage from '../components/AdminPage.svelte';
    import { provideI18n } from '../lib/i18n';
    type Data = Record<string, any>;
    type I18n = { locale: string; messages: Record<string, string|string[]> };
    type Boot = { page: string; props: Data; themes: Data[]; theme: Data; debug: boolean; i18n?: I18n };
    type CredentialField = { input: string; label: string; required: boolean; secret: boolean; default?: string };
    type ProviderDefinition = { label: string; user_managed: boolean; credentials: Record<string, CredentialField> };
    type PermissionDefinition = { id: string; label: string; description?: string|null; scopeKinds: string[] };
    type ActionGroup = { id: string; label: string; description?: string|null; permissionIds: string[] };
    let { boot }: { boot: Boot } = $props();
    provideI18n(() => boot.i18n?.messages ?? {});
    const p = $derived(boot.props), user = $derived(p.user ?? p.currentUser ?? null), csrf = $derived(p.csrfToken ?? '');
    let dark = $state(document.documentElement.classList.contains('dark'));
    let menu = $state(false), filter = $state(''), score = $state<number|null>(null), passkeyError = $state(''), busy = $state(false), keyName = $state('');
    const list = <T=Data>(v: T[]|null|undefined): T[] => v ?? [];
    const enc = (v: unknown) => encodeURIComponent(String(v ?? ''));
    const permission = (v: string) => list(user?.roles).some(r => list<string>(r.permissions).includes(v));
    const recordType = (r: Data) => typeof r.type === 'string' ? r.type : r.type?.value ?? '';
    const providerDefinitions = (v: unknown): [string, ProviderDefinition][] => Object.entries((v ?? {}) as Record<string, ProviderDefinition>);
    const credentialFields = (v: ProviderDefinition): CredentialField[] => Object.values(v.credentials ?? {});
    const permissionDefinitions = $derived(list<PermissionDefinition>(p.permissionDefinitions));
    const actionGroups = $derived(list<ActionGroup>(p.actionGroups));
    const groupedPermissionIds = $derived(new Set(actionGroups.flatMap(group => group.permissionIds)));
    const ungroupedPermissions = $derived(permissionDefinitions.filter(definition => !groupedPermissionIds.has(definition.id)));
    const interpolate = (text: string, parameters: Record<string, string|number> = {}) => text.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, key) => String(parameters[key] ?? `{${key}}`));
    const t = (key: string, parameters: Record<string, string|number> = {}) => { const message = boot.i18n?.messages[key]; return interpolate(Array.isArray(message) ? message[0] : message ?? key, parameters); };
    const tp = (key: string, count: number, parameters: Record<string, string|number> = {}) => { const message = boot.i18n?.messages[key]; const template = Array.isArray(message) ? message[count === 1 ? 0 : 1] : message ?? key; return interpolate(template, { ...parameters, count }); };
    const permissionLabel = (permissionId: string) => t(permissionDefinitions.find(definition => definition.id === permissionId)?.label ?? permissionId);
    const actionGroupLabel = (group: ActionGroup) => t(group.label);
    const ask = (e: SubmitEvent, text: string) => { if (!confirm(text)) e.preventDefault(); };
    const strength = (e: Event) => { const value=(e.currentTarget as HTMLInputElement).value; void import('zxcvbn').then(({default:zxcvbn})=>score=zxcvbn(value).score); };
    function setDark(v: boolean) { dark=v; document.documentElement.classList.toggle('dark',v); localStorage.setItem('towerdns-color-mode',v?'dark':'light'); }
    const toBuf=(s:string)=>{const b=s.replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(b+'='.repeat((4-b.length%4)%4)),c=>c.charCodeAt(0)).buffer};
    const toB64=(b:ArrayBuffer)=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
    async function loginPasskey(){busy=true;passkeyError='';try{const o=JSON.parse(p.optionsJson);o.challenge=toBuf(o.challenge);o.allowCredentials=list(o.allowCredentials).map(c=>({...c,id:toBuf(c.id)}));const a=await navigator.credentials.get({publicKey:o}) as PublicKeyCredential|null;if(!a)throw Error(t('passkey.error.no-authenticator-response'));const r=a.response as AuthenticatorAssertionResponse;const res=await fetch('/login/webauthn/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:toB64(a.rawId),rawId:toB64(a.rawId),type:a.type,response:{clientDataJSON:toB64(r.clientDataJSON),authenticatorData:toB64(r.authenticatorData),signature:toB64(r.signature),userHandle:r.userHandle?toB64(r.userHandle):null}})});const d=await res.json();if(!res.ok)throw Error(d.error??t('auth.error.login-failed'));location.href=d.redirect??'/';}catch(e){passkeyError=e instanceof Error?e.message:t('auth.error.login-failed');busy=false;}}
    async function registerPasskey(){if(!keyName.trim()){passkeyError=t('passkey.error.name-required');return}busy=true;passkeyError='';try{const begin=await fetch('/profile/webauthn/register/begin',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`name=${enc(keyName)}&csrf_token=${enc(csrf)}`});const o=await begin.json();if(!begin.ok)throw Error(o.error??t('passkey.error.start-failed'));o.challenge=toBuf(o.challenge);o.user={...o.user,id:toBuf(o.user.id)};o.excludeCredentials=list(o.excludeCredentials).map(c=>({...c,id:toBuf(c.id)}));const c=await navigator.credentials.create({publicKey:o}) as PublicKeyCredential|null;if(!c)throw Error(t('passkey.error.no-authenticator-response'));const r=c.response as AuthenticatorAttestationResponse;const done=await fetch('/profile/webauthn/register/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:toB64(c.rawId),rawId:toB64(c.rawId),type:c.type,response:{clientDataJSON:toB64(r.clientDataJSON),attestationObject:toB64(r.attestationObject)}})});const d=await done.json();if(!done.ok)throw Error(d.error??t('passkey.error.registration-failed'));location.reload();}catch(e){passkeyError=e instanceof Error?e.message:t('passkey.error.registration-failed');busy=false;}}
</script>

<a class="skip-link" href="#main-content">{t('navigation.skip-to-content')}</a>
{#if user}<nav class="navbar"><div class="navbar-brand"><a class="navbar-item brand" href="/">TowerDNS</a><button class="navbar-burger" aria-label={t('navigation.menu')} onclick={()=>menu=!menu}><span></span><span></span><span></span></button></div><div class:open={menu} class="navbar-menu"><div class="navbar-start"><a class="navbar-item" href="/zones">{t('navigation.zones')}</a><a class="navbar-item" href="/accounts">{t('navigation.accounts')}</a>{#if permission('user.manage')}<a class="navbar-item" href="/users">{t('navigation.users')}</a>{/if}{#if permission('role.manage')}<a class="navbar-item" href="/roles">{t('navigation.roles')}</a>{/if}{#if permission('system.settings.manage')}<a class="navbar-item" href="/settings">{t('navigation.settings')}</a>{/if}{#if permission('provider.config.manage')}<a class="navbar-item" href="/credentials">{t('navigation.providers')}</a>{/if}</div><div class="navbar-end"><div class="navbar-item"><Switch checked={dark} onCheckedChange={(d)=>setDark(d.checked)} class="theme-switch" label={t('theme.label')}><Switch.Label>{dark?t('theme.dark'):t('theme.light')}</Switch.Label><Switch.Control class="theme-switch__control preset-filled-primary-500"><Switch.Thumb class="theme-switch__thumb">{dark?'☾':'☀'}</Switch.Thumb></Switch.Control><Switch.HiddenInput/></Switch></div><a class="navbar-item" href="/profile">{user.displayName||user.email}</a><form class="navbar-item" method="post" action="/logout"><input type="hidden" name="csrf_token" value={csrf}><button class="button is-small">{t('auth.logout')}</button></form></div></div></nav>{/if}

<main class:auth-page={!user} id="main-content">
{#if boot.debug}<Notice kind="warning" text={t('notice.debug-enabled')}/>{/if}
{#if ['login','forgot_password','reset_password','mfa_totp'].includes(boot.page)}
 <section class="auth-card box"><a class="wordmark" href="/">TowerDNS</a><h1 class="title is-4">{boot.page==='login'?t('auth.welcome-back'):boot.page==='forgot_password'?t('auth.forgot-password'):boot.page==='reset_password'?t('auth.new-password'):t('auth.two-factor')}</h1>{#if p.error}<Notice kind="danger" text={p.error}/>{/if}{#if p.sent}<Notice kind="success" text={t('auth.reset-email-sent')}/>{:else}<form method="post" action={boot.page==='login'?'/login':boot.page==='forgot_password'?'/password/forgot':boot.page==='reset_password'?'/password/reset':'/login/totp'}><input type="hidden" name="csrf_token" value={csrf}>{#if p.token}<input type="hidden" name="token" value={p.token}>{/if}{#if ['login','forgot_password'].includes(boot.page)}<Field label={t('field.email')}><input class="input" name="email" type="email" autocomplete="email" required></Field>{/if}{#if boot.page==='login'}<Field label={t('field.password')}><input class="input" name="password" type="password" autocomplete="current-password" required></Field>{/if}{#if boot.page==='reset_password'}<Field label={t('field.new-password')}><input class="input" name="password" type="password" oninput={strength} required><Strength value={score}/></Field><Field label={t('field.repeat')}><input class="input" name="password_confirm" type="password" required></Field>{/if}{#if boot.page==='mfa_totp'}<Field label={t('field.authenticator-code')}><input class="input code-input" name="code" inputmode="numeric" pattern={'[0-9]{6,8}'} required></Field>{/if}<button class="button is-primary is-fullwidth">{boot.page==='login'?t('auth.login'):boot.page==='forgot_password'?t('auth.send-reset-link'):boot.page==='reset_password'?t('common.save'):t('common.confirm')}</button></form>{/if}<div class="auth-links"><a href={boot.page==='login'?'/password/forgot':'/login'}>{boot.page==='login'?t('auth.forgot-password-question'):t('auth.back-to-login')}</a></div></section>
{:else if boot.page==='login_webauthn'}<section class="auth-card box"><a class="wordmark" href="/">TowerDNS</a><h1 class="title is-4">{t('auth.login-with-passkey')}</h1>{#if p.error||passkeyError}<Notice kind="danger" text={p.error||passkeyError}/>{/if}<button class:loading={busy} class="button is-primary is-fullwidth" onclick={loginPasskey}>{t('auth.use-passkey')}</button><div class="auth-links"><a href="/login">{t('auth.other-login-method')}</a></div></section>
{:else if boot.page==='dashboard'}<Page title={t('page.dashboard.title')} subtitle={t('dashboard.welcome',{name:user.displayName||user.email})}><div class="dashboard-grid"><Feature title={t('dashboard.zones.title')} text={t('dashboard.zones.text')} href="/zones"/><Feature title={t('dashboard.accounts.title')} text={t('dashboard.accounts.text')} href="/accounts"/><Feature title={t('dashboard.security.title')} text={t('dashboard.security.text')} href="/profile"/></div></Page>
{:else if boot.page==='zones/list'}<Page title={t('page.zones.title')} error={p.error}>{#each list(p.providers) as provider}<section class="box"><h2 class="subtitle">{provider.displayName}</h2><form class="inline-form" method="post" action={`/zones/${enc(provider.id)}`}><input type="hidden" name="csrf_token" value={csrf}><input class="input" name="zone_name" placeholder="example.com" required><button class="button is-primary">{t('zones.create')}</button></form>{#if p.fetchErrors?.[provider.id]}<Notice kind="warning" text={p.fetchErrors[provider.id]}/>{/if}<div class="resource-grid">{#each list(p.zonesByProvider?.[provider.id]) as zone}<article class="resource-card"><div><a class="resource-title" href={`/zones/${enc(provider.id)}/${enc(zone.id)}`}>{zone.name}</a><span class:active={zone.active} class="status">{zone.active?t('status.active'):t('status.inactive')}</span></div><form method="post" action={`/zones/${enc(provider.id)}/${enc(zone.id)}/delete`} onsubmit={(e)=>ask(e,t('zones.confirm-delete',{name:zone.name}))}><input type="hidden" name="csrf_token" value={csrf}><button class="button is-small is-danger">{t('common.delete')}</button></form></article>{:else}<p class="empty">{t('zones.empty')}</p>{/each}</div></section>{:else}<Notice kind="info" text={t('providers.none-configured')}/>{/each}</Page>
{:else if boot.page==='zones/records'}<Page title={p.zoneId} error={p.error} success={p.success}><div class="page-actions"><a class="button" href="/zones">← {t('navigation.zones')}</a><a class="button" href={`/zones/${enc(p.providerId)}/${enc(p.zoneId)}/dnssec`}>DNSSEC</a></div><section class="box"><h2 class="subtitle">{t('rrset.save')}</h2><p class="muted">{t('rrset.save-hint')}</p><form method="post" action={`/zones/${enc(p.providerId)}/${enc(p.zoneId)}/rrsets`}><input type="hidden" name="csrf_token" value={csrf}><div class="form-grid"><Field label={t('field.name')}><input class="input" name="name" value="@" required></Field><Field label={t('field.type')}><input class="input" name="type" placeholder="TLSA / TYPE65400" required></Field><Field label="TTL"><input class="input" name="ttl" type="number" min="30" max="604800" value="300" required></Field></div><Field label="RDATA"><textarea class="input" name="rdata" rows="4" required></textarea></Field><button class="button is-primary">{t('rrset.save')}</button></form></section><div class="filter-bar"><input class="input" bind:value={filter} placeholder={t('rrset.search')}></div><table class="table"><thead><tr><th>{t('field.name')}</th><th>{t('field.type')}</th><th>TTL</th><th>RDATA</th><th></th></tr></thead><tbody>{#each list(p.rrsets).filter(r=>JSON.stringify(r).toLowerCase().includes(filter.toLowerCase())) as r}<tr><td><code>{r.ownerName}</code></td><td>{r.type?.presentation??r.type}</td><td>{r.ttl}</td><td><code>{list(r.rdata).join('\n')}</code></td><td class="actions"><form method="post" action={`/zones/${enc(p.providerId)}/${enc(p.zoneId)}/rrsets/${enc(r.ownerName)}/${enc(r.type?.presentation??r.type)}/delete`} onsubmit={(e)=>ask(e,t('rrset.confirm-delete'))}><input type="hidden" name="csrf_token" value={csrf}><button class="button is-small is-danger">{t('rrset.delete')}</button></form></td></tr>{/each}</tbody></table></Page>
{:else if boot.page==='profile/index'}<Page title={t('page.profile.title')} error={p.error} success={p.success} narrow><section class="box"><form method="post" action="/profile"><input type="hidden" name="csrf_token" value={csrf}><Field label={t('field.display-name')}><input class="input" name="display_name" value={user.displayName??''}></Field><Field label={t('field.theme')}><select class="input" name="theme"><option value="system" selected={user.theme==='system'}>{t('theme.system')}</option>{#each boot.themes as theme}<option value={theme.name} selected={user.theme===theme.name}>{theme.displayName}</option>{/each}</select></Field><button class="button is-primary">{t('common.save')}</button></form></section><div class="settings-list"><Setting title={t('profile.password.title')} text={t('profile.password.text')} href="/profile/password"/><Setting title="TOTP" text={p.totpEnabled?t('status.active'):t('profile.totp.not-configured')} href="/profile/totp"/><Setting title={t('profile.passkeys.title')} text={tp('profile.passkeys.registered',list(p.webAuthnKeys).length)} href="/profile/webauthn"/><Setting title={t('profile.api-keys.title')} text={t('profile.api-keys.text')} href="/profile/api-keys"/></div></Page>
{:else if boot.page==='profile/password'}<Page title={t('profile.password.title')} error={p.error} success={p.success} narrow><section class="box"><form method="post"><input type="hidden" name="csrf_token" value={csrf}><Field label={t('profile.password.current')}><input class="input" type="password" name="current_password" required></Field><Field label={t('field.new-password')}><input class="input" type="password" name="new_password" oninput={strength} required><Strength value={score}/></Field><Field label={t('field.repeat')}><input class="input" type="password" name="new_password_confirm" required></Field><button class="button is-primary">{t('profile.password.change')}</button></form></section></Page>
{:else if boot.page==='profile/totp'}<Page title={t('auth.two-factor')} error={p.error} success={p.success} narrow><Notice kind="warning" text={t('profile.totp.notice')}/><section class="box"><span class:active={p.totpActive} class="status">{p.totpActive?t('status.active'):t('status.inactive')}</span>{#if p.provisioningUri}<p class="mt-4"><a class="button is-fullwidth" href={p.provisioningUri}>{t('profile.totp.open-authenticator')}</a></p><Field label={t('profile.totp.secret')}><input class="input" readonly value={p.secretFormatted}></Field>{/if}<form method="post"><input type="hidden" name="csrf_token" value={csrf}><input type="hidden" name="action" value={p.totpActive?'disable':'enable'}><Field label={t('profile.totp.current-code')}><input class="input code-input" name="code" inputmode="numeric" pattern={'[0-9]{6,8}'} required></Field><button class:is-danger={p.totpActive} class="button is-primary">{p.totpActive?t('common.disable'):t('common.enable')}</button></form></section></Page>
{:else if boot.page==='profile/webauthn'}<Page title={t('profile.passkeys.title')} error={p.error} success={p.success} narrow><section class="box"><div class="inline-form"><input class="input" bind:value={keyName} placeholder={t('profile.passkeys.name')}><button class:loading={busy} class="button is-primary" onclick={registerPasskey}>{t('profile.passkeys.register')}</button></div>{#if passkeyError}<Notice kind="danger" text={passkeyError}/>{/if}</section><DataTable rows={list(p.keys)} cols={['name','created_at','last_used_at']} labels={[t('field.name'),t('table.registered'),t('table.last-used')]} {csrf} action={(r)=>`/profile/webauthn/${r.credential_id_url}/delete`} actionText={t('common.remove')}/></Page>
{:else if boot.page==='profile/api_keys'}<Page title={t('profile.api-keys.title')} error={p.error} success={p.success} narrow>{#if p.newToken}<Notice kind="warning" text={t('profile.api-keys.copy-token',{token:p.newToken})}/>{/if}<section class="box"><form class="inline-form" method="post"><input type="hidden" name="csrf_token" value={csrf}><input class="input" name="name" placeholder={t('field.name')} required><button class="button is-primary">{t('common.create')}</button></form></section><DataTable rows={list(p.keys)} cols={['name','created_at','last_used']} labels={[t('field.name'),t('table.created'),t('table.last-used')]} {csrf} action={(r)=>`/profile/api-keys/${r.id}/revoke`} actionText={t('profile.api-keys.revoke')}/></Page>
{:else if boot.page==='zones/record_edit'}<Page title={t('page.record-edit.title')} error={p.error} narrow>{#if p.record}<section class="box"><form method="post" action={`/zones/${enc(p.providerId)}/${enc(p.zoneId)}/records/${enc(p.record.id)}/update`}><input type="hidden" name="csrf_token" value={csrf}><div class="form-grid"><Field label={t('field.name')}><input class="input" name="name" value={p.record.name} required></Field><Field label="TTL"><input class="input" name="ttl" type="number" value={p.record.ttl} required></Field><Field label={t('field.content')}><input class="input" name="content" value={p.record.content} required></Field></div><button class="button is-primary">{t('common.save')}</button></form></section>{/if}</Page>
{:else if boot.page==='zones/dnssec'}<Page title={`${t('page.dnssec.title')} · ${p.zoneId}`} error={p.error} success={p.success} narrow><section class="box"><p>{t('dnssec.status')}: <strong>{t(`dnssec.state.${p.profile?.state??'unknown'}`)}</strong></p><form class="buttons mt-4" method="post"><input type="hidden" name="csrf_token" value={csrf}><button class="button is-primary" name="action" value="enable">{t('common.enable')}</button><button class="button is-danger" name="action" value="disable">{t('common.disable')}</button></form></section></Page>
{:else if boot.page==='accounts/list'}<Page title={t('page.accounts.title')} error={p.error}><section class="box"><form class="form-grid" method="post"><input type="hidden" name="csrf_token" value={csrf}><Field label={t('field.name')}><input class="input" name="name" required></Field><Field label={t('field.slug')}><input class="input" name="slug" pattern={'[a-z0-9-]{2,64}'} required></Field><button class="button is-primary">{t('accounts.create')}</button></form></section><div class="resource-grid">{#each list(p.accounts) as account}<article class="resource-card"><a class="resource-title" href={`/accounts/${account.id}`}>{account.name}</a><div class="buttons"><a class="button is-small" href={`/accounts/${account.id}/members`}>{t('accounts.members')}</a><a class="button is-small" href={`/accounts/${account.id}/providers`}>{t('navigation.providers')}</a></div></article>{/each}</div></Page>
{:else if boot.page==='iam/users'}<Page title={t('page.users.title')} error={p.error} success={p.success}><section class="box"><form class="form-grid" method="post" action="/users"><input type="hidden" name="csrf_token" value={csrf}><Field label={t('field.email')}><input class="input" type="email" name="email" required></Field><Field label={t('field.password')}><input class="input" type="password" name="password" oninput={strength} required><Strength value={score}/></Field><button class="button is-primary">{t('users.create')}</button></form></section><DataTable rows={list(p.users)} cols={['email','displayName']} labels={[t('field.email'),t('field.display-name')]}/></Page>
{:else if boot.page==='iam/roles'}<Page title={t('page.roles.title')} error={p.error} success={p.success}><section class="box"><form method="post" action="/roles"><input type="hidden" name="csrf_token" value={csrf}><Field label={t('field.name')}><input class="input" name="name" required></Field>{#each actionGroups as group}<fieldset class="permission-group"><legend>{actionGroupLabel(group)}</legend>{#if group.description}<p class="muted">{t(group.description)}</p>{/if}<div class="form-grid">{#each group.permissionIds as permissionId}<label class="checkbox"><input type="checkbox" name="permissions[]" value={permissionId}> {permissionLabel(permissionId)}</label>{/each}</div></fieldset>{/each}{#if ungroupedPermissions.length}<fieldset class="permission-group"><legend>{t('roles.individual-permissions')}</legend><div class="form-grid">{#each ungroupedPermissions as permission}<label class="checkbox"><input type="checkbox" name="permissions[]" value={permission.id}> {t(permission.label)}</label>{/each}</div></fieldset>{/if}<button class="button is-primary mt-4">{t('roles.create')}</button></form></section><section class="box"><h2 class="subtitle">{t('roles.existing')}</h2><div class="resource-grid">{#each list(p.roles) as role}<article class="resource-card"><div><a class="resource-title" href={`/roles/${enc(role.id)}`}>{role.name}</a><span class="status">{role.isBuiltIn?t('roles.built-in'):t('roles.custom')}</span></div></article>{:else}<p class="empty">{t('roles.empty')}</p>{/each}</div></section></Page>
{:else if boot.page==='iam/role_edit'}<Page title={p.role?.name??t('page.role-edit.title')} error={p.error} success={p.success} narrow><div class="page-actions"><a class="button" href="/roles">← {t('page.roles.title')}</a></div>{#if p.role}<section class="box"><form method="post"><input type="hidden" name="csrf_token" value={csrf}><Field label={t('field.name')}><input class="input" name="name" value={p.role.name} readonly={p.role.isBuiltIn} required></Field>{#each actionGroups as group}<fieldset class="permission-group" disabled={p.role.isBuiltIn}><legend>{actionGroupLabel(group)}</legend>{#if group.description}<p class="muted">{t(group.description)}</p>{/if}<div class="form-grid">{#each group.permissionIds as permissionId}<label class="checkbox"><input type="checkbox" name="permissions[]" value={permissionId} checked={list<string>(p.role.permissions).includes(permissionId)}> {permissionLabel(permissionId)}</label>{/each}</div></fieldset>{/each}{#if ungroupedPermissions.length}<fieldset class="permission-group" disabled={p.role.isBuiltIn}><legend>{t('roles.individual-permissions')}</legend><div class="form-grid">{#each ungroupedPermissions as permission}<label class="checkbox"><input type="checkbox" name="permissions[]" value={permission.id} checked={list<string>(p.role.permissions).includes(permission.id)}> {t(permission.label)}</label>{/each}</div></fieldset>{/if}{#if p.role.isBuiltIn}<Notice kind="info" text={t('roles.built-in-read-only')}/>{:else}<button class="button is-primary">{t('common.save')}</button>{/if}</form></section>{/if}</Page>
{:else if boot.page==='credentials'}<Page title={t('page.credentials.title')} error={p.error} success={p.success}>{#each providerDefinitions(p.providerDefinitions) as [providerId,provider]}<section class="box"><h2 class="subtitle">{provider.label} {p.configured?.[providerId]?`· ${t('status.configured')}`:''}</h2><form method="post"><input type="hidden" name="csrf_token" value={csrf}><input type="hidden" name="provider" value={providerId}><div class="form-grid">{#each credentialFields(provider) as field}<Field label={field.label}><input class="input" type={field.secret?'password':'text'} name={field.input} value={p.values?.[field.input]??field.default??''} required={field.required}></Field>{/each}</div><button class="button is-primary">{t('common.save')}</button></form></section>{/each}</Page>
{:else if boot.page==='settings'}<Page title={t('page.settings.title')} error={p.error} success={p.success} narrow><form method="post"><input type="hidden" name="csrf_token" value={csrf}><section class="box"><Field label={t('settings.application-name')}><input class="input" name="app_name" value={p.fields?.app_name}></Field><Field label={t('settings.hostname')}><input class="input" name="app_hostname" value={p.fields?.app_hostname}></Field><Field label={t('field.theme')}><select class="input" name="theme_name">{#each boot.themes as theme}<option value={theme.name} selected={theme.name===p.fields?.theme_name}>{theme.displayName}</option>{/each}</select></Field><label class="checkbox"><input type="checkbox" name="app_force_https" value="1" checked={p.fields?.app_force_https}> {t('settings.force-https')}</label><label class="checkbox"><input type="checkbox" name="app_debug" value="1" checked={p.fields?.app_debug}> {t('settings.debug')}</label></section><section class="box form-grid"><Field label={t('settings.password-min-length')}><input class="input" type="number" name="pwd_min_length" value={p.fields?.pwd_min_length}></Field><Field label={t('settings.password-min-score')}><input class="input" type="number" name="pwd_min_score" value={p.fields?.pwd_min_score}></Field><Field label={t('settings.mailer-dsn')}><input class="input" name="mailer_dsn" value={p.fields?.mailer_dsn}></Field><Field label={t('settings.sender')}><input class="input" type="email" name="mailer_from_address" value={p.fields?.mailer_from_address}></Field></section><button class="button is-primary">{t('common.save')}</button></form></Page>
{:else}<Page title={boot.page.split('/').slice(-1)[0]?.replace(/_/g,' ')??'TowerDNS'} error={p.error} success={p.success}><AdminPage page={boot.page} data={p} {csrf}/></Page>{/if}
</main>
