<script lang="ts">
    import { Switch } from '@skeletonlabs/skeleton-svelte';
    import Page from '../components/Page.svelte';
    import Field from '../components/Field.svelte';
    import Notice from '../components/Notice.svelte';
    import Strength from '../components/Strength.svelte';
    import Feature from '../components/Feature.svelte';
    import Setting from '../components/Setting.svelte';
    import DataTable from '../components/DataTable.svelte';
    import AdminPage from '../components/AdminPage.svelte';
    type Data = Record<string, any>;
    type Boot = { page: string; props: Data; themes: Data[]; theme: Data; debug: boolean };
    type CredentialField = { input: string; label: string; required: boolean; secret: boolean; default?: string };
    type ProviderDefinition = { label: string; user_managed: boolean; credentials: Record<string, CredentialField> };
    let { boot }: { boot: Boot } = $props();
    const p = $derived(boot.props), user = $derived(p.user ?? p.currentUser ?? null), csrf = $derived(p.csrfToken ?? '');
    let dark = $state(document.documentElement.classList.contains('dark'));
    let menu = $state(false), filter = $state(''), score = $state<number|null>(null), passkeyError = $state(''), busy = $state(false), keyName = $state('');
    const list = <T=Data>(v: T[]|null|undefined): T[] => v ?? [];
    const enc = (v: unknown) => encodeURIComponent(String(v ?? ''));
    const permission = (v: string) => list(user?.roles).some(r => list<string>(r.permissions).includes(v));
    const recordType = (r: Data) => typeof r.type === 'string' ? r.type : r.type?.value ?? '';
    const providerDefinitions = (v: unknown): [string, ProviderDefinition][] => Object.entries((v ?? {}) as Record<string, ProviderDefinition>);
    const credentialFields = (v: ProviderDefinition): CredentialField[] => Object.values(v.credentials ?? {});
    const ask = (e: SubmitEvent, text: string) => { if (!confirm(text)) e.preventDefault(); };
    const strength = (e: Event) => { const value=(e.currentTarget as HTMLInputElement).value; void import('zxcvbn').then(({default:zxcvbn})=>score=zxcvbn(value).score); };
    function setDark(v: boolean) { dark=v; document.documentElement.classList.toggle('dark',v); localStorage.setItem('towerdns-color-mode',v?'dark':'light'); }
    const toBuf=(s:string)=>{const b=s.replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(b+'='.repeat((4-b.length%4)%4)),c=>c.charCodeAt(0)).buffer};
    const toB64=(b:ArrayBuffer)=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
    async function loginPasskey(){busy=true;passkeyError='';try{const o=JSON.parse(p.optionsJson);o.challenge=toBuf(o.challenge);o.allowCredentials=list(o.allowCredentials).map(c=>({...c,id:toBuf(c.id)}));const a=await navigator.credentials.get({publicKey:o}) as PublicKeyCredential|null;if(!a)throw Error('Keine Antwort vom Authenticator.');const r=a.response as AuthenticatorAssertionResponse;const res=await fetch('/login/webauthn/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:toB64(a.rawId),rawId:toB64(a.rawId),type:a.type,response:{clientDataJSON:toB64(r.clientDataJSON),authenticatorData:toB64(r.authenticatorData),signature:toB64(r.signature),userHandle:r.userHandle?toB64(r.userHandle):null}})});const d=await res.json();if(!res.ok)throw Error(d.error??'Anmeldung fehlgeschlagen.');location.href=d.redirect??'/';}catch(e){passkeyError=e instanceof Error?e.message:'Anmeldung fehlgeschlagen.';busy=false;}}
    async function registerPasskey(){if(!keyName.trim()){passkeyError='Bitte eine Bezeichnung eingeben.';return}busy=true;passkeyError='';try{const begin=await fetch('/profile/webauthn/register/begin',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:`name=${enc(keyName)}&csrf_token=${enc(csrf)}`});const o=await begin.json();if(!begin.ok)throw Error(o.error??'Start fehlgeschlagen.');o.challenge=toBuf(o.challenge);o.user={...o.user,id:toBuf(o.user.id)};o.excludeCredentials=list(o.excludeCredentials).map(c=>({...c,id:toBuf(c.id)}));const c=await navigator.credentials.create({publicKey:o}) as PublicKeyCredential|null;if(!c)throw Error('Keine Antwort vom Authenticator.');const r=c.response as AuthenticatorAttestationResponse;const done=await fetch('/profile/webauthn/register/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:toB64(c.rawId),rawId:toB64(c.rawId),type:c.type,response:{clientDataJSON:toB64(r.clientDataJSON),attestationObject:toB64(r.attestationObject)}})});const d=await done.json();if(!done.ok)throw Error(d.error??'Registrierung fehlgeschlagen.');location.reload();}catch(e){passkeyError=e instanceof Error?e.message:'Registrierung fehlgeschlagen.';busy=false;}}
</script>

<a class="skip-link" href="#main-content">Zum Hauptinhalt</a>
{#if user}<nav class="navbar"><div class="navbar-brand"><a class="navbar-item brand" href="/">TowerDNS</a><button class="navbar-burger" aria-label="Menü" onclick={()=>menu=!menu}><span></span><span></span><span></span></button></div><div class:open={menu} class="navbar-menu"><div class="navbar-start"><a class="navbar-item" href="/zones">Zonen</a><a class="navbar-item" href="/accounts">Accounts</a>{#if permission('user.manage')}<a class="navbar-item" href="/users">Benutzer</a>{/if}{#if permission('role.manage')}<a class="navbar-item" href="/roles">Rollen</a>{/if}{#if permission('system.settings.manage')}<a class="navbar-item" href="/settings">Einstellungen</a>{/if}{#if permission('provider.credentials.manage')}<a class="navbar-item" href="/credentials">Provider</a>{/if}</div><div class="navbar-end"><div class="navbar-item"><Switch checked={dark} onCheckedChange={(d)=>setDark(d.checked)} class="theme-switch" label="Farbschema"><Switch.Label>{dark?'Dunkel':'Hell'}</Switch.Label><Switch.Control class="theme-switch__control preset-filled-primary-500"><Switch.Thumb class="theme-switch__thumb">{dark?'☾':'☀'}</Switch.Thumb></Switch.Control><Switch.HiddenInput/></Switch></div><a class="navbar-item" href="/profile">{user.displayName||user.email}</a><form class="navbar-item" method="post" action="/logout"><input type="hidden" name="csrf_token" value={csrf}><button class="button is-small">Abmelden</button></form></div></div></nav>{/if}

<main class:auth-page={!user} id="main-content">
{#if boot.debug}<Notice kind="warning" text="Debug-Modus ist aktiv."/>{/if}
{#if ['login','forgot_password','reset_password','mfa_totp'].includes(boot.page)}
 <section class="auth-card box"><a class="wordmark" href="/">TowerDNS</a><h1 class="title is-4">{boot.page==='login'?'Willkommen zurück':boot.page==='forgot_password'?'Passwort vergessen':boot.page==='reset_password'?'Neues Passwort':'Zwei-Faktor-Anmeldung'}</h1>{#if p.error}<Notice kind="danger" text={p.error}/>{/if}{#if p.sent}<Notice kind="success" text="Falls das Konto existiert, wurde eine E-Mail versendet."/>{:else}<form method="post" action={boot.page==='login'?'/login':boot.page==='forgot_password'?'/password/forgot':boot.page==='reset_password'?'/password/reset':'/login/totp'}><input type="hidden" name="csrf_token" value={csrf}>{#if p.token}<input type="hidden" name="token" value={p.token}>{/if}{#if ['login','forgot_password'].includes(boot.page)}<Field label="E-Mail"><input class="input" name="email" type="email" autocomplete="email" required></Field>{/if}{#if boot.page==='login'}<Field label="Passwort"><input class="input" name="password" type="password" autocomplete="current-password" required></Field>{/if}{#if boot.page==='reset_password'}<Field label="Neues Passwort"><input class="input" name="password" type="password" oninput={strength} required><Strength value={score}/></Field><Field label="Wiederholen"><input class="input" name="password_confirm" type="password" required></Field>{/if}{#if boot.page==='mfa_totp'}<Field label="Authenticator-Code"><input class="input code-input" name="code" inputmode="numeric" pattern={'[0-9]{6,8}'} required></Field>{/if}<button class="button is-primary is-fullwidth">{boot.page==='login'?'Anmelden':boot.page==='forgot_password'?'Reset-Link senden':boot.page==='reset_password'?'Speichern':'Bestätigen'}</button></form>{/if}<div class="auth-links"><a href={boot.page==='login'?'/password/forgot':'/login'}>{boot.page==='login'?'Passwort vergessen?':'Zur Anmeldung'}</a></div></section>
{:else if boot.page==='login_webauthn'}<section class="auth-card box"><a class="wordmark" href="/">TowerDNS</a><h1 class="title is-4">Mit Passkey anmelden</h1>{#if p.error||passkeyError}<Notice kind="danger" text={p.error||passkeyError}/>{/if}<button class:loading={busy} class="button is-primary is-fullwidth" onclick={loginPasskey}>Passkey verwenden</button><div class="auth-links"><a href="/login">Andere Anmeldeart</a></div></section>
{:else if boot.page==='dashboard'}<Page title="Dashboard" subtitle={`Willkommen, ${user.displayName||user.email}.`}><div class="dashboard-grid"><Feature title="DNS-Zonen" text="Zonen, Records und DNSSEC verwalten." href="/zones"/><Feature title="Accounts" text="Teams und Provider organisieren." href="/accounts"/><Feature title="Kontosicherheit" text="Passkeys, TOTP und API-Schlüssel." href="/profile"/></div></Page>
{:else if boot.page==='zones/list'}<Page title="DNS-Zonen" error={p.error}>{#each list(p.providers) as provider}<section class="box"><h2 class="subtitle">{provider.displayName}</h2><form class="inline-form" method="post" action={`/zones/${enc(provider.id)}`}><input type="hidden" name="csrf_token" value={csrf}><input class="input" name="zone_name" placeholder="example.com" required><button class="button is-primary">Zone anlegen</button></form>{#if p.fetchErrors?.[provider.id]}<Notice kind="warning" text={p.fetchErrors[provider.id]}/>{/if}<div class="resource-grid">{#each list(p.zonesByProvider?.[provider.id]) as zone}<article class="resource-card"><div><a class="resource-title" href={`/zones/${enc(provider.id)}/${enc(zone.id)}`}>{zone.name}</a><span class:active={zone.active} class="status">{zone.active?'Aktiv':'Inaktiv'}</span></div><form method="post" action={`/zones/${enc(provider.id)}/${enc(zone.id)}/delete`} onsubmit={(e)=>ask(e,`Zone ${zone.name} löschen?`)}><input type="hidden" name="csrf_token" value={csrf}><button class="button is-small is-danger">Löschen</button></form></article>{:else}<p class="empty">Keine Zonen.</p>{/each}</div></section>{:else}<Notice kind="info" text="Kein Provider konfiguriert."/>{/each}</Page>
{:else if boot.page==='zones/records'}<Page title={p.zoneId} error={p.error} success={p.success}><div class="page-actions"><a class="button" href="/zones">← Zonen</a><a class="button" href={`/zones/${enc(p.providerId)}/${enc(p.zoneId)}/dnssec`}>DNSSEC</a></div><section class="box"><h2 class="subtitle">RRset speichern</h2><p class="muted">Ein Zeile pro RDATA-Wert. Speichern ersetzt das vollständige RRset und liest es zur Prüfung erneut vom Provider.</p><form method="post" action={`/zones/${enc(p.providerId)}/${enc(p.zoneId)}/rrsets`}><input type="hidden" name="csrf_token" value={csrf}><div class="form-grid"><Field label="Name"><input class="input" name="name" value="@" required></Field><Field label="Typ"><input class="input" name="type" placeholder="TLSA oder TYPE65400" required></Field><Field label="TTL"><input class="input" name="ttl" type="number" min="30" max="604800" value="300" required></Field></div><Field label="RDATA"><textarea class="input" name="rdata" rows="4" required></textarea></Field><button class="button is-primary">RRset speichern</button></form></section><div class="filter-bar"><input class="input" bind:value={filter} placeholder="RRsets durchsuchen …"></div><table class="table"><thead><tr><th>Name</th><th>Typ</th><th>TTL</th><th>RDATA</th><th></th></tr></thead><tbody>{#each list(p.rrsets).filter(r=>JSON.stringify(r).toLowerCase().includes(filter.toLowerCase())) as r}<tr><td><code>{r.ownerName}</code></td><td>{r.type?.presentation??r.type}</td><td>{r.ttl}</td><td><code>{list(r.rdata).join('\n')}</code></td><td class="actions"><form method="post" action={`/zones/${enc(p.providerId)}/${enc(p.zoneId)}/rrsets/${enc(r.ownerName)}/${enc(r.type?.presentation??r.type)}/delete`} onsubmit={(e)=>ask(e,'Gesamtes RRset löschen?')}><input type="hidden" name="csrf_token" value={csrf}><button class="button is-small is-danger">RRset löschen</button></form></td></tr>{/each}</tbody></table></Page>
{:else if boot.page==='profile/index'}<Page title="Mein Profil" error={p.error} success={p.success} narrow><section class="box"><form method="post" action="/profile"><input type="hidden" name="csrf_token" value={csrf}><Field label="Anzeigename"><input class="input" name="display_name" value={user.displayName??''}></Field><Field label="Theme"><select class="input" name="theme"><option value="system" selected={user.theme==='system'}>Systemeinstellung</option>{#each boot.themes as t}<option value={t.name} selected={user.theme===t.name}>{t.displayName}</option>{/each}</select></Field><button class="button is-primary">Speichern</button></form></section><div class="settings-list"><Setting title="Passwort" text="Anmeldepasswort ändern" href="/profile/password"/><Setting title="TOTP" text={p.totpEnabled?'Aktiv':'Nicht eingerichtet'} href="/profile/totp"/><Setting title="Passkeys" text={`${list(p.webAuthnKeys).length} registriert`} href="/profile/webauthn"/><Setting title="API-Schlüssel" text="Zugriff verwalten" href="/profile/api-keys"/></div></Page>
{:else if boot.page==='profile/password'}<Page title="Passwort ändern" error={p.error} success={p.success} narrow><section class="box"><form method="post"><input type="hidden" name="csrf_token" value={csrf}><Field label="Aktuelles Passwort"><input class="input" type="password" name="current_password" required></Field><Field label="Neues Passwort"><input class="input" type="password" name="new_password" oninput={strength} required><Strength value={score}/></Field><Field label="Wiederholen"><input class="input" type="password" name="new_password_confirm" required></Field><button class="button is-primary">Ändern</button></form></section></Page>
{:else if boot.page==='profile/totp'}<Page title="Zwei-Faktor-Authentifizierung" error={p.error} success={p.success} narrow><Notice kind="warning" text="TowerDNS nutzt SHA-512 und 8-stellige Codes. Verwende Aegis oder FreeOTP+."/><section class="box"><span class:active={p.totpActive} class="status">{p.totpActive?'Aktiv':'Inaktiv'}</span>{#if p.provisioningUri}<p class="mt-4"><a class="button is-fullwidth" href={p.provisioningUri}>In Authenticator öffnen</a></p><Field label="Geheimer Schlüssel"><input class="input" readonly value={p.secretFormatted}></Field>{/if}<form method="post"><input type="hidden" name="csrf_token" value={csrf}><input type="hidden" name="action" value={p.totpActive?'disable':'enable'}><Field label="Aktueller Code"><input class="input code-input" name="code" inputmode="numeric" pattern={'[0-9]{6,8}'} required></Field><button class:is-danger={p.totpActive} class="button is-primary">{p.totpActive?'Deaktivieren':'Aktivieren'}</button></form></section></Page>
{:else if boot.page==='profile/webauthn'}<Page title="Passkeys" error={p.error} success={p.success} narrow><section class="box"><div class="inline-form"><input class="input" bind:value={keyName} placeholder="Bezeichnung"><button class:loading={busy} class="button is-primary" onclick={registerPasskey}>Registrieren</button></div>{#if passkeyError}<Notice kind="danger" text={passkeyError}/>{/if}</section><DataTable rows={list(p.keys)} cols={['name','created_at','last_used_at']} labels={['Name','Registriert','Zuletzt genutzt']} {csrf} action={(r)=>`/profile/webauthn/${r.credential_id_url}/delete`} actionText="Entfernen"/></Page>
{:else if boot.page==='profile/api_keys'}<Page title="API-Schlüssel" error={p.error} success={p.success} narrow>{#if p.newToken}<Notice kind="warning" text={`Jetzt kopieren: ${p.newToken}`}/>{/if}<section class="box"><form class="inline-form" method="post"><input type="hidden" name="csrf_token" value={csrf}><input class="input" name="name" placeholder="Bezeichnung" required><button class="button is-primary">Erstellen</button></form></section><DataTable rows={list(p.keys)} cols={['name','created_at','last_used']} labels={['Name','Erstellt','Zuletzt']} {csrf} action={(r)=>`/profile/api-keys/${r.id}/revoke`} actionText="Widerrufen"/></Page>
{:else if boot.page==='zones/record_edit'}<Page title="Record bearbeiten" error={p.error} narrow>{#if p.record}<section class="box"><form method="post" action={`/zones/${enc(p.providerId)}/${enc(p.zoneId)}/records/${enc(p.record.id)}/update`}><input type="hidden" name="csrf_token" value={csrf}><div class="form-grid"><Field label="Name"><input class="input" name="name" value={p.record.name} required></Field><Field label="TTL"><input class="input" name="ttl" type="number" value={p.record.ttl} required></Field><Field label="Inhalt"><input class="input" name="content" value={p.record.content} required></Field></div><button class="button is-primary">Speichern</button></form></section>{/if}</Page>
{:else if boot.page==='zones/dnssec'}<Page title={`DNSSEC · ${p.zoneId}`} error={p.error} success={p.success} narrow><section class="box"><p>Status: <strong>{p.profile?.state??'Unbekannt'}</strong></p><form class="buttons mt-4" method="post"><input type="hidden" name="csrf_token" value={csrf}><button class="button is-primary" name="action" value="enable">Aktivieren</button><button class="button is-danger" name="action" value="disable">Deaktivieren</button></form></section></Page>
{:else if boot.page==='accounts/list'}<Page title="Accounts" error={p.error}><section class="box"><form class="form-grid" method="post"><input type="hidden" name="csrf_token" value={csrf}><Field label="Name"><input class="input" name="name" required></Field><Field label="Slug"><input class="input" name="slug" pattern={'[a-z0-9-]{2,64}'} required></Field><button class="button is-primary">Account anlegen</button></form></section><div class="resource-grid">{#each list(p.accounts) as a}<article class="resource-card"><a class="resource-title" href={`/accounts/${a.id}`}>{a.name}</a><div class="buttons"><a class="button is-small" href={`/accounts/${a.id}/members`}>Mitglieder</a><a class="button is-small" href={`/accounts/${a.id}/providers`}>Provider</a></div></article>{/each}</div></Page>
{:else if boot.page==='iam/users'}<Page title="Benutzerverwaltung" error={p.error} success={p.success}><section class="box"><form class="form-grid" method="post" action="/users"><input type="hidden" name="csrf_token" value={csrf}><Field label="E-Mail"><input class="input" type="email" name="email" required></Field><Field label="Passwort"><input class="input" type="password" name="password" oninput={strength} required><Strength value={score}/></Field><button class="button is-primary">Benutzer anlegen</button></form></section><DataTable rows={list(p.users)} cols={['email','displayName']} labels={['E-Mail','Anzeigename']}/></Page>
{:else if boot.page==='iam/roles'}<Page title="Rollenverwaltung" error={p.error} success={p.success}><section class="box"><form method="post" action="/roles"><input type="hidden" name="csrf_token" value={csrf}><Field label="Name"><input class="input" name="name" required></Field><div class="form-grid">{#each list(p.permissions) as perm}<label class="checkbox"><input type="checkbox" name="permissions[]" value={perm}> {perm}</label>{/each}</div><button class="button is-primary mt-4">Rolle anlegen</button></form></section><DataTable rows={list(p.roles)} cols={['name','isSystem']} labels={['Name','Systemrolle']}/></Page>
{:else if boot.page==='credentials'}<Page title="Provider-Zugangsdaten" error={p.error} success={p.success}>{#each providerDefinitions(p.providerDefinitions) as [providerId,provider]}<section class="box"><h2 class="subtitle">{provider.label} {p.configured?.[providerId]?'· konfiguriert':''}</h2><form method="post"><input type="hidden" name="csrf_token" value={csrf}><input type="hidden" name="provider" value={providerId}><div class="form-grid">{#each credentialFields(provider) as field}<Field label={field.label}><input class="input" type={field.secret?'password':'text'} name={field.input} value={p.values?.[field.input]??field.default??''} required={field.required}></Field>{/each}</div><button class="button is-primary">Speichern</button></form></section>{/each}</Page>
{:else if boot.page==='settings'}<Page title="Systemeinstellungen" error={p.error} success={p.success} narrow><form method="post"><input type="hidden" name="csrf_token" value={csrf}><section class="box"><Field label="Anwendungsname"><input class="input" name="app_name" value={p.fields?.app_name}></Field><Field label="Hostname"><input class="input" name="app_hostname" value={p.fields?.app_hostname}></Field><Field label="Theme"><select class="input" name="theme_name">{#each boot.themes as t}<option value={t.name} selected={t.name===p.fields?.theme_name}>{t.displayName}</option>{/each}</select></Field><label class="checkbox"><input type="checkbox" name="app_force_https" value="1" checked={p.fields?.app_force_https}> HTTPS erzwingen</label><label class="checkbox"><input type="checkbox" name="app_debug" value="1" checked={p.fields?.app_debug}> Debug</label></section><section class="box form-grid"><Field label="Passwort-Mindestlänge"><input class="input" type="number" name="pwd_min_length" value={p.fields?.pwd_min_length}></Field><Field label="Mindeststärke"><input class="input" type="number" name="pwd_min_score" value={p.fields?.pwd_min_score}></Field><Field label="Mailer-DSN"><input class="input" name="mailer_dsn" value={p.fields?.mailer_dsn}></Field><Field label="Absender"><input class="input" type="email" name="mailer_from_address" value={p.fields?.mailer_from_address}></Field></section><button class="button is-primary">Speichern</button></form></Page>
{:else}<Page title={boot.page.split('/').slice(-1)[0]?.replace(/_/g,' ')??'TowerDNS'} error={p.error} success={p.success}><AdminPage page={boot.page} data={p} {csrf}/></Page>{/if}
</main>
